### ISSUE TITLE
Support for input fields of search type

### ISSUE THREAD

**Issue by vaultor** [svivian/sv-filtable-js#5]
For input text fields used for the filters, only `type="text"` seems to be supported.
Please consider also supporting `type="search"`, as filter fields are sort of like search fields too, and we can benefit from the built-in "clear" button implemented by popular browsers.

**Comment by svivian** [comment]
Yes that's a fair point. I'll look at adding that.

**Comment by vaultor** [comment]
I have made some changes locally while awaiting the next release, hopefully this helps anyone in the same boat:
- added `input[type="search"]` to the selector type to include search inputs as well.
- changed the event type from `keyup` to `input`. So that changes to the input value, including clicking the built-in "clear" button of search inputs, or clearing the field with JavaScript, will always trigger the filter to run.


```
// Line 10, sv-filtable.js
// control types with events
const controlTypes = {
  text: {
    selector: 'input[type="text"], input[type="search"]',
    event: "input",
  },
  ...
};
```

**Comment by svivian** [comment]
Thanks! I've added that to the latest release.
