### ISSUE TITLE
Throws invalid column error with no table rows

### ISSUE THREAD

**Issue by vaultor** [svivian/sv-filtable-js#6]
If there are no table body rows, an error is thrown in the console:
`Uncaught Error: invalid column specified in data-filter-col attribute`

I have made sure `data-filter-col` specified are correct (zero-indexed), and no error is thrown when there are one or more rows.

**Comment by svivian** [comment]
What is the use case here? Are you starting with an empty table and then adding the data dynamically later?

When loading Filtable it checks that the table has the columns specified in the filters, e.g. if a filter has `data-filter-col="4"`you must have at least 5 columns. (It also checks the table body rather than the headers to allow colspans in the headers)

**Comment by vaultor** [comment]
Yes, we show an empty table then add data dynamically later as users fill in the search criteria.
For simplicity, we setup sort and filter when DOM is loaded without extraneous checks.
I can either suppress the error with try-catch or do a row count check before loading Filtable, if the error is intended.

**Comment by svivian** [comment]
It doesn’t have to be an error, I think I just added that to have a friendly message instead of an error later on when doing the filtering. Maybe it makes more sense to add that check when the filtering is actually done.

**Comment by vaultor** [comment]
It would definitely help to not be an error.
Or have Filtable avoid checking col integrity if there are no body rows.

There are also scenarios where a search yields no results, and showing an empty table to users makes sense.
Most devs wouldn't expect to perform a row count check before running `new SV.Filtable(table, controlPanel);`, so if this check isn't required, it would simplify things a lot.

**Comment by svivian** [comment]
Finally got around to looking at this. I've updated it to stop building the filters if there are no rows in the table yet. They are rebuilt each time any filtering occurs anyway. Thanks for the suggestion!
